apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: jxilt/server:latest
        ports:
        - containerPort: 10005

---

apiVersion: v1
kind: Service
metadata:
    name: server-entrypoint
spec:
    type: LoadBalancer
    selector:
      app: server
    ports:
    - port: 10005