use std::str::Utf8Error;

/// A common class for errors generated by the server.
#[derive(Debug)]
pub struct ServerError {
    pub(crate) message: String
}

impl From<Utf8Error> for ServerError {
    fn from(_err: Utf8Error) -> Self {
        return ServerError::new("Request contained invalid UTF-8.".to_string());
    }
}

impl ServerError {
    pub fn new(message: String) -> ServerError {
        ServerError { message }
    }
}

pub(crate) type Result<T> = std::result::Result<T, ServerError>;